name: "ocr"

services:
  api:
    container_name: ocr
    build:
      context: .
      dockerfile: Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      TESSERACT__PATH: "/usr/share/tesseract-ocr/5/tessdata"
      TESSERACT__LANGUAGE: "rus+eng"
    volumes:
      - /Users/vadislavzainullin/MEGAsync/tesseract:/usr/share/tesseract-ocr/5/tessdata
    ports:
      - "7207:8080"